In [10]:
#panda is a fast , powerful,flexible and easy to use open source data analysis and manipulation tool
#built on top of the python programming Language 
#2008 , Mckinney
#very well with structured data
#woking with commma seperated values is csv files

In [11]:
import pandas as pd

In [12]:
df=pd.read_csv('services.csv')  #Read a comma seperated values(csv0 files inyo DATAFRAMES

In [13]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [14]:
df= pd.read_csv('services.csv', header= None)  #internal integer indexes  are provided by pandas
df

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
1,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
2,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
3,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
4,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
5,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
6,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
7,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
8,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
9,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
10,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
11,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
12,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
13,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
14,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
15,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
16,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
17,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
18,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
19,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
20,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
21,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
22,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
23,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [15]:
df = pd.read_csv('services.csv', skiprows =2) 
df

,2,2.1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligible people age 55 or over who meet certain income qualifications.,"Age 55 or over, county resident and willing and able to work. Income requirements vary according to program",Unnamed: 9,...,Unnamed: 12,"EMPLOYMENT/TRAINING SERVICES, Job Development, Job Information/Placement/Referral, Job Training, Job Training Formats, Job Search/Placement, Older Adults",Unnamed: 14,Second Career Employment Program,Unnamed: 16,San Mateo County,active,Varies.,Unnamed: 20,Unnamed: 21
0,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
1,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
2,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
3,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
4,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
5,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
6,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
7,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
8,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
10,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
12,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
13,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
14,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
15,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
16,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
17,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
18,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
19,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
20,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [16]:
 pd.read_csv('services.csv', usecols = ['program_id','application_process'])

    program_id                                application_process
0          NaN                         Walk in or apply by phone.
1          NaN                 Apply by phone for an appointment.
2          NaN        Phone for information (403-4300 Ext. 4322).
3          NaN                                    Apply by phone.
4          NaN                             Phone for information.
5          NaN  Walk in or apply by phone for membership appli...
6          NaN  Apply by phone or be referred by a doctor, soc...
7          NaN                                    Apply by phone.
8          NaN  Walk in. Proof of residency in California requ...
9          NaN  Walk in. Proof of California residency to rece...
10         NaN  Walk in. Proof of California residency require...
11         NaN  Walk in or apply by phone, email or webpage re...
12         NaN  Walk in. Proof of California residency require...
13         NaN  Call for appointment. Referral from human serv...
14         NaN          Walk in or through other agency referral.
15         NaN  Walk in. Written application, identification r...
16         NaN                              Call for information.
17         NaN  Call for screening appointment. Medical visits...
18         NaN     Call for screening appointment (650-347-3648).
19         NaN                                           Walk in.
20         NaN                    By phone during business hours.
21         NaN                  Walk in or apply by phone or mail
22         NaN                  Walk in or apply by phone or mail

In [17]:
df

,2,2.1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligible people age 55 or over who meet certain income qualifications.,"Age 55 or over, county resident and willing and able to work. Income requirements vary according to program",Unnamed: 9,...,Unnamed: 12,"EMPLOYMENT/TRAINING SERVICES, Job Development, Job Information/Placement/Referral, Job Training, Job Training Formats, Job Search/Placement, Older Adults",Unnamed: 14,Second Career Employment Program,Unnamed: 16,San Mateo County,active,Varies.,Unnamed: 20,Unnamed: 21
0,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
1,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
2,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
3,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
4,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
5,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
6,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
7,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
8,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
10,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
12,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
13,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
14,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
15,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
16,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
17,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
18,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
19,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
20,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [18]:
#data structure used in pandas is  both series and dataframes 
#dataframes are combination of rows and column
#series >> 1 dimensional in  nature(only row or column )
#dataframes >> 2 dimensional in nature,  multiple series constitutes to form the dataframes

In [19]:
type(df)

pandas.core.frame.DataFrame

In [20]:
df

,2,2.1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligible people age 55 or over who meet certain income qualifications.,"Age 55 or over, county resident and willing and able to work. Income requirements vary according to program",Unnamed: 9,...,Unnamed: 12,"EMPLOYMENT/TRAINING SERVICES, Job Development, Job Information/Placement/Referral, Job Training, Job Training Formats, Job Search/Placement, Older Adults",Unnamed: 14,Second Career Employment Program,Unnamed: 16,San Mateo County,active,Varies.,Unnamed: 20,Unnamed: 21
0,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
1,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
2,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
3,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
4,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
5,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
6,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
7,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
8,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
10,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
12,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
13,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
14,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
15,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
16,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
17,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
18,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
19,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
20,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [21]:
s=df.application_process

AttributeError: 'DataFrame' object has no attribute 'application_process'

In [ ]:
type(s)

In [25]:
df['Varies']

KeyError: 'Varies'

In [26]:
l=[1,2,3,4]
s= pd.Series(l)
s

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
type(s)  #0,1,2,3 are the index of the element

In [27]:
s[0]

1

In [ ]:
s[1]

In [ ]:
s[2]

In [ ]:
s[3]

In [28]:
s[2:4]

2    3
3    4
dtype: int64

In [29]:
s[2:]

2    3
3    4
dtype: int64

In [38]:
d=pd.Series([100,200,300], index = ["Ajay","Bijay","Sanjay"])

In [32]:
d

Ajay      100
Bijay     200
Sanjay    300
dtype: int64

In [33]:
type(d)

pandas.core.series.Series

In [34]:
d['Ajay']

100

In [39]:
d.index

Index(['Ajay', 'Bijay', 'Sanjay'], dtype='object')

In [ ]:
d["Ajay":"Sanjay"]

In [42]:
d.reset_index()   #this will convert the table to into dataframe by adding one new indices 
d

Ajay      100
Bijay     200
Sanjay    300
dtype: int64

In [41]:
d.reset_index(drop=True)   #This will drop the original indices and give a new indices

0    100
1    200
2    300
dtype: int64

In [43]:
pd.DataFrame(d)

          0
Ajay    100
Bijay   200
Sanjay  300

In [44]:
df = pd.read_csv('services.csv')
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [45]:
df.shape

(23, 22)

In [46]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [47]:
list(df.columns)

['id',
 'location_id',
 'program_id',
 'accepted_payments',
 'alternate_name',
 'application_process',
 'audience',
 'description',
 'eligibility',
 'email',
 'fees',
 'funding_sources',
 'interpretation_services',
 'keywords',
 'languages',
 'name',
 'required_documents',
 'service_areas',
 'status',
 'wait_time',
 'website',
 'taxonomy_ids']

In [ ]:
df.head(2) # uper se doh data

In [ ]:
df.tail(5) # niche se 2 data

In [48]:
df.sample(2)   # koi bhi 2 data pure data se

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN

In [49]:
df.sample(1) #koi bhi data pura tables se

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN

In [50]:

#let see the data types 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       23 non-null     int64
 1   location_id              23 non-null     int64
 2   program_id               0 non-null      float64
 3   accepted_payments        1 non-null      object
 4   alternate_name           1 non-null      object
 5   application_process      23 non-null     object
 6   audience                 14 non-null     object
 7   description              23 non-null     object
 8   eligibility              17 non-null     object
 9   email                    1 non-null      object
 10  fees                     21 non-null     object
 11  funding_sources          21 non-null     object
 12  interpretation_services  1 non-null      object
 13  keywords                 21 non-null     object
 14  languages                1 non-null      object
 15  name                     23 non-null     object
 16  required_documents       1 non-null      object
 17  service_areas            21 non-null     object
 18  status                   23 non-null     object
 19  wait_time                19 non-null     object
 20  website                  2 non-null      object
 21  taxonomy_ids             1 non-null      object
dtypes: float64(1), int64(2), object(19)
memory usage: 4.1+ KB

In [51]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [52]:
#value of a particular datatypes
df['location_id']

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    22
Name: location_id, dtype: int64

In [53]:
df['application_process']

0                            Walk in or apply by phone.
1                    Apply by phone for an appointment.
2           Phone for information (403-4300 Ext. 4322).
3                                       Apply by phone.
4                                Phone for information.
5     Walk in or apply by phone for membership appli...
6     Apply by phone or be referred by a doctor, soc...
7                                       Apply by phone.
8     Walk in. Proof of residency in California requ...
9     Walk in. Proof of California residency to rece...
10    Walk in. Proof of California residency require...
11    Walk in or apply by phone, email or webpage re...
12    Walk in. Proof of California residency require...
13    Call for appointment. Referral from human serv...
14            Walk in or through other agency referral.
15    Walk in. Written application, identification r...
16                                Call for information.
17    Call for screening appointment. Medical visits...
18       Call for screening appointment (650-347-3648).
19                                             Walk in.
20                      By phone during business hours.
21                    Walk in or apply by phone or mail
22                    Walk in or apply by phone or mail
Name: application_process, dtype: object

In [ ]:
type(df['application_process'])

In [ ]:
list[df['application_process']]

In [54]:
#series to dataframes 
s=pd.Series([2,3,4], index =[100,'Ajay',2])
s

100     2
Ajay    3
2       4
dtype: int64

In [55]:
d = pd.DataFrame(s)

In [56]:
d

      0
100   2
Ajay  3
2     4

In [ ]:
d['new column'] = "Bijay"  #this is not good practice to put space in between the column indexes

In [ ]:
d

In [ ]:
d.new_column

In [ ]:
d.reset_index()

In [ ]:
d.reset_index(drop=True)

In [ ]:
df.columns

In [ ]:
df.required_documents

In [ ]:
df_subsets=df[['name','languages', 'status']]
df_subsets

In [ ]:
df1 = pd.read_excel("LUSID Excel - Setting up your market data.xlsx")

In [ ]:
df1.columns

In [ ]:
df1.shape

In [ ]:
df1.info

In [ ]:
pd.read_csv("taxonomy.csv")

In [ ]:
#reading csv from  some url
df3=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [ ]:
df3.columns

In [ ]:
df3.shape

In [ ]:
df3.dtypes

In [ ]:
df3['Sex']

In [ ]:
df3.columns

In [ ]:
df3[['PassengerId','Fare','Pclass']]

In [ ]:
#padas give you the liberty to read the table from html page

In [ ]:
pip install lxml

In [ ]:
import lxml

In [ ]:
import pandas as pd 
url_df=pd.read_html("https://www.basketball-reference.com/leagues/NBA_2015_totals.html")

In [ ]:
type(url_df)

In [ ]:
df4=url_df[0]

In [ ]:
df4

In [ ]:
df4.shape

In [ ]:
df4.head()

In [ ]:
df4.info

In [ ]:
df4.columns

In [ ]:
df4.to_csv("players.csv",index= False)

In [ ]:
#read the data from json format  #json dataset are the data that stores the data in key value pair

In [ ]:
url="https://api.github.com/repos/pandas-dev/pandas/issues"
pd.read_json(url)

In [ ]:
import requests 
data = requests.get(url)

In [ ]:
data

In [ ]:
df6= data.json()

In [ ]:
df6

In [ ]:
len(df6)

In [ ]:
for i in range(len(df)): 
    print(df6[i]['user'])

In [59]:
#Solving data sets
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [60]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df.head()

In [ ]:
df.dtypes

In [ ]:
df.info()

In [57]:
df.describe() #give the statistical information about numerical column

             id  location_id  program_id
count  23.00000    23.000000         0.0
mean   12.00000    11.956522         NaN
std     6.78233     6.711444         NaN
min     1.00000     1.000000         NaN
25%     6.50000     6.500000         NaN
50%    12.00000    12.000000         NaN
75%    17.50000    17.500000         NaN
max    23.00000    22.000000         NaN

In [61]:
df[['PassengerId','Survived','Pclass']]

     PassengerId  Survived  Pclass
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

[891 rows x 3 columns]

In [62]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [63]:
df.dtypes == 'object'  #object here is the string data types

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [64]:
df.dtypes[df.dtypes  == 'object'].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [65]:
df[df.dtypes[df.dtypes == 'object'].index]

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [66]:
df[df.dtypes[df.dtypes == 'object'].index].describe()

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [67]:
df.describe(include = 'object')  #note the statistical information doesn't make much sense with respect to string value

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [68]:
df.describe(include = 'all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,B96 B98,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [ ]:
df.describe() #gives the five point summary it is nothing but min , 25percentile , 50 percentile, 75 percentile , 100 percentile and max value is nothing but the five point summmary

In [ ]:
df.astype('object').describe() #gives the statistical information considering categorical column

In [ ]:
df[0:100:5]

In [ ]:
df['new_col']='pwskills'

In [ ]:
df

In [69]:
df['family']=df['SibSp'] + df['Parch']

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  family       891 non-null    int64
dtypes: float64(2), int64(6), object(5)
memory usage: 90.6+ KB

In [71]:
pd.Categorical(df['Pclass']) #different  categories of pclasss

[3, 1, 3, 1, 3, ..., 2, 1, 3, 1, 3]
Length: 891
Categories (3, int64): [1, 2, 3]

In [72]:
pd.Categorical(df['Cabin'])

[NaN, 'C85', NaN, 'C123', NaN, ..., NaN, 'B42', NaN, 'C148', NaN]
Length: 891
Categories (147, object): ['A10', 'A14', 'A16', 'A19', ..., 'F38', 'F4', 'G6', 'T']

In [73]:
df['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

In [74]:
df['Cabin'].nunique()

147

In [ ]:
df['Cabin']

In [ ]:
df['Cabin'].value_counts() #unique count

In [76]:
#How many passenger are 5 year old 

df[df['Age'] < 5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,family
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S,4
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S,2
16,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q,5
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C,3
63,64,0,3,"Skoog, Master. Harald",male,4.00,3,2,347088,27.9000,NaN,S,5
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S,2
119,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S,6
164,165,0,3,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,39.6875,NaN,S,5
171,172,0,3,"Rice, Master. Arthur",male,4.00,4,1,382652,29.1250,NaN,Q,5
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S,2
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S,3
184,185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,315153,22.0250,NaN,S,2
193,194,1,2,"Navratil, Master. Michel M",male,3.00,1,1,230080,26.0000,F2,S,2
205,206,0,3,"Strom, Miss. Telma Matilda",female,2.00,0,1,347054,10.4625,G6,S,1
261,262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,31.3875,NaN,S,6
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,3
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,3
340,341,1,2,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,26.0000,F2,S,2
348,349,1,3,"Coutts, Master. William Loch ""William""",male,3.00,1,1,C.A. 37671,15.9000,NaN,S,2
374,375,0,3,"Palsson, Miss. Stina Viola",female,3.00,3,1,349909,21.0750,NaN,S,4
381,382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.00,0,2,2653,15.7417,NaN,C,2
386,387,0,3,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,46.9000,NaN,S,7
407,408,1,2,"Richards, Master. William Rowe",male,3.00,1,1,29106,18.7500,NaN,S,2
445,446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,A34,S,2
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C,3
479,480,1,3,"Hirvonen, Miss. Hildur E",female,2.00,0,1,3101298,12.2875,NaN,S,1
530,531,1,2,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,26.0000,NaN,S,2
618,619,1,2,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,39.0000,F4,S,3
642,643,0,3,"Skoog, Miss. Margit Elizabeth",female,2.00,3,2,347088,27.9000,NaN,S,5
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C,3
691,692,1,3,"Karun, Miss. Manca",female,4.00,0,1,349256,13.4167,NaN,C,1
750,751,1,2,"Wells, Miss. Joan",female,4.00,1,1,29103,23.0000,NaN,S,2
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S,2
788,789,1,3,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,20.5750,NaN,S,3
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C,1
824,825,0,3,"Panula, Master. Urho Abraham",male,2.00,4,1,3101295,39.6875,NaN,S,5
827,828,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,NaN,C,2
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S,2
850,851,0,3,"Andersson, Master. Sigvard Harald Elias",male,4.00,4,2,347082,31.2750,NaN,S,6
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S,2

In [ ]:
len(df[df['Age']<5])

In [ ]:
df[df['Age'] < 5].Name

In [ ]:
list(df[df['Age'] < 5].Name)

In [ ]:
#how many person are less than 18 years old 
list(df[df['Age']>18].Name)

In [ ]:
df['Fare'].mean()

In [ ]:
#q: How  many passangers have paid less than avg fare 
df[df['Fare'] < df['Fare'].mean()]

In [ ]:
len(df[df['Fare'] < df['Fare'].mean()])

In [ ]:
#how many passengers paid a fare
len(df[df['Fare']==0])

In [ ]:
df[df['Sex']=='male']

In [ ]:
len(df[df['Sex']=='male'])

In [ ]:
len(df[df['Sex']=='female'])

In [ ]:
df['Sex'].value_counts(normalize= True )

In [ ]:
#how many passenger of class 1
df[df['Pclass']==1]

In [ ]:
#how many passanger surived 
df[df['Survived']==1]

In [ ]:
len(df[df['Survived']==1])

In [ ]:
df['Survived'].value_counts(normalize =  True)

In [ ]:
#how many females paid more than avg fare

In [ ]:
df['Sex']=='Female'

In [ ]:
df['Fare'].mean()

In [ ]:
df[(df['Sex']=='female') & (df['Fare'] > df['Fare'].mean())]

In [ ]:
len(df[(df['Sex']=='female') & (df['Fare'] > df['Fare'].mean())])

In [ ]:
len(df[(df['Sex']=='male') & (df['Fare'] > df['Fare'].mean())])

In [ ]:
import numpy as np
np.mean(df.Fare)

In [ ]:
df.Fare.mean()

In [ ]:
max(df.Fare)

In [ ]:
min(df['Fare'])

In [ ]:
df[df['Fare']==max(df.Fare)]

In [ ]:
df[df['Fare']==max(df.Fare)].Name

In [ ]:
df[(df.Age > 18) & (df['Survived'] == 1)]

In [ ]:
#Lecture pandas Advance 2

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [ ]:
df

In [ ]:
#slicing the dataframes is nothing but accessing  the data from dataframes

In [ ]:
df[0:100]

In [ ]:
#access rows and column of dataframes>> implict /internal/integer  indexing  or explicit/named indexing

In [ ]:
df.iloc[0:2]  #i stand for implict /internal/integer indexing

In [ ]:
df

In [ ]:
df.loc[0:2]#loc is used for named indexing , iloc is used for integer indexing

In [ ]:
df

In [ ]:
#df.iloc[0:2, ['Name', 'Parch']] #it will throw an error

In [ ]:
df.loc[0:2 , ["Name","Parch"]]  #name indexing is done through loc

In [ ]:
df.iloc[0:2 , 3:6]    #column indexing start from zero

In [ ]:
list(df['Name'][2:5])

In [ ]:
s=pd.Series(list(df['Name'][2:5]), index=['a','b','c'])

In [ ]:
s

In [ ]:
s1=pd.Series(list(df['Name'][5:8]))

In [ ]:
s

In [ ]:
"pw" + "skills"

In [ ]:
s + s1 #series with different indexes Cannnot be concatenated

In [ ]:
#if  you keep the index same , then for series concatnenation can happen

In [ ]:
s

In [ ]:
s1= pd.Series(list(df['Name'][5:8]), index=['a','b','c'])

In [ ]:
s

In [ ]:
s+s1

In [ ]:
df

In [ ]:
df.drop('PassengerId', axis = 1)  # remove the passennger id from csv files axis=1 denotes that it is a column files

In [ ]:
df

In [ ]:
#drop row wise

In [ ]:
df.drop(1,inplace = True)

In [ ]:
df

In [ ]:
df.reset_index()

In [ ]:
#set name column as index
df.set_index('Name', inplace= True)

In [ ]:
df

In [ ]:
df.loc['Braund, Mr. Owen Harris']

In [ ]:
df.reset_index(inplace= True)

In [ ]:
df

In [ ]:
d=  {'key1':[2,3,4,5],
    'key2':[4,5,6,7],
    'key3':[2,3,4,5]}

In [ ]:
d

In [ ]:
pd.DataFrame(d)

In [ ]:
d=  {'key1':(2,3,4,5),
    'key2':(4,5,6,7),
    'key3':(2,3,4,5)}

In [ ]:
d

In [ ]:
pd.DataFrame(d)

In [ ]:
df1=pd.read_csv("taxonomy.csv")

In [ ]:
df1

In [ ]:
df1.shape

In [ ]:
df1.describe()

In [ ]:
df1.info()

In [ ]:
#know the count of the nul  value

In [ ]:
df1.isnull().sum()  ##give the sum of null value present

In [ ]:
#droping the null value row wise
df1.dropna()

In [ ]:
df1  #orginal dataframe is not true ;  for doing so write inplace = true in previous command

In [ ]:
#drop column wise 
df1.dropna(axis=1)

In [ ]:
df1[['name']].dropna(axis=1) #for one column

In [ ]:
#impuation of missing value 
#numeric data >> we can replace with the mean and median >> if outlier are treated >> replace with mean or median
#categorical data can be replaced  by >>  mode 
#impute missing value with some constant

In [ ]:
df1.fillna("somevalue")

In [ ]:
df1.fillna(0)

In [ ]:
df1.parent_id

In [ ]:
df1.parent_id.fillna()  #since parentid is a object thus , we have to first convert to integer and find out mean then only  we can replace with mean

In [ ]:
data1 = {
    'A': [1, 2, None, 4, 5, None, 7, 8, 9, 10],
    'B': [None, 11, 12, 13, None, 15, 16, None, 18, 19]
}
df2=pd.DataFrame(data1)
df2

In [ ]:
df2.A.fillna(df2['A'].mean)

In [ ]:
df2.A.fillna(df2['A'].median)

In [ ]:
df2

In [ ]:
df2.fillna(0)

In [ ]:
df2.fillna('something')

In [ ]:
df2.fillna(method='ffill')  #see from bottom and fill with next observed value

In [ ]:
df2.fillna(method='bfill') #see from top and fill with  next observed value

In [ ]:
df2.duplicated().sum()

In [ ]:
#more functions 
df.mean()

In [ ]:
df.median()

In [ ]:
df.std()

In [ ]:
df.Age.describe()

In [ ]:
df

In [ ]:
#what is the avg fare paid by people who surive
df[df.Survived==1]['Fare'].mean()

In [ ]:
#what is the avg fare paid by people who didn't surive

df[df.Survived==0]['Fare'].mean()

In [ ]:
#grouby

In [ ]:
#grouby function is used to find the required(avg/min/max) value for every atttribute baed on the given  condition


df.groupby('Survived').mean(numeric_only=True)

In [ ]:
#min value 

df.groupby('Survived').min(numeric_only=True)

In [ ]:
#sum value 

df.groupby('Survived').sum(numeric_only=True)

In [ ]:
#25 percentile // 50 percentile and other parameter in describe 
df.groupby('Survived').describe()

In [ ]:
df[['Survived','Fare']]

In [ ]:
import numpy as np
df.groupby(['Survived'])['Fare'].agg([min,'max','mean','median','count',np.std,'var'])

In [ ]:
#working of group by

In [ ]:
df.groupby(['Sex','Pclass'])['Survived'].sum()

In [ ]:
df.groupby(['Sex','Pclass'])['Survived'].sum().to_frame()

In [ ]:
df.groupby(['Sex','Pclass'])['Survived'].sum().unstack()

In [ ]:
a=df.groupby('Pclass').sum(numeric_only = True)

In [ ]:
a

In [ ]:
a.T

In [ ]:
a.transpose()

In [ ]:
df.head()

In [ ]:
df.head().T

In [ ]:
#Lecture 3

In [ ]:
#conctenation of data

df=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [ ]:
df1=df[["Name","Sex","Age"]][0:5]

In [ ]:
df2=df[["Name","Sex","Age"]][5:10]

In [ ]:
pd.concat([df1,df2],axis=0)

In [ ]:
pd.concat([df1,df2],axis=1)

In [ ]:
df2=df2.reset_index(drop=True)

In [ ]:
pd.concat([df1,df2], axis = 1)

In [ ]:
#merge and join (inner join is the intersection,left join is the all the element of left set similarly with right join iis nothing but all the element of the right join    )

In [ ]:
df1=pd.DataFrame({'key1':[1,2,4,5,6],'key2':[4,5,6,7,8],'key3':[3,4,5,6,6]})
df2= pd.DataFrame({'key1':[1,2,45,6,67],'key4':[56,5,6,7,8],'key5':[3,56,5,6,6]})

In [ ]:
df1

In [ ]:
df2

In [ ]:
#merge 
pd.merge(df1, df2, how="inner")

In [ ]:
pd.merge(df1,df2,how='left')

In [ ]:
pd.merge(df1,df2,how='right')

In [ ]:
pd.merge(df1,df2, how ='outer')

In [ ]:
pd.merge(df1,df2,how='cross')  #Every element of df1 is mapped to the other element of df2

In [ ]:
pd.merge(df1,df2, how ='left', left_on="key2", right_on="key4")

In [ ]:
#join uses the index where as merge uses the keys 
df1= pd.DataFrame({'key1':[1,2,4,5,6],
                  'key2':[4,5,6,7,8],
                  'key3':[3,4,5,6,6]},
                 index=['a','b','c','d','e']
                 )

In [ ]:
df2= pd.DataFrame({'key6':[1,2,45,6,67],
                  'key4':[56,5,6,7,8],
                  'key5':[3,56,5,6,6]},
                 index=['a','b','h','i','j']
                 )

In [ ]:
df1

In [ ]:
df2

In [ ]:
df1.join(df2, how = "inner") #join column of another dataframes

In [ ]:
df1.join(df2, how = "left")

In [ ]:
df1.join(df2, how = "right")

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [ ]:
df['Fare_inr']=df['Fare'].apply(lambda x: x*84) #apply function given in a[[ly

In [ ]:
#df[df.Sex=="Female" & df.Age<=25 & df.Survived==1]

In [ ]:
df

In [ ]:
#women with less age than 25 and sex is female and survived
#df[(df['Sex']=='female') & (df['Age']<=25) & (df['Survived']==1)]

In [ ]:
df['Fare_inr']

In [ ]:
len("Ram")

In [ ]:
df['Name_len']=df['Name'].apply(len)

In [ ]:
df['Name_len']

In [ ]:
def convert(x):
    return x*90

In [ ]:
df['Fare_1']=df['Fare'].apply(convert)

In [ ]:
df['Fare_1']

In [ ]:
def create_flag(x):
    if x<10:
        return "Cheap"
    elif x >10 and x <20:
        return "Medium"
    else:
        return "High"

In [ ]:
df['flag_fare']=df['Fare'].apply(create_flag)

In [ ]:
data = {"a":[1,2,3,4],
        "b":[5,5,6,7],
        "c":["pw","skills","aj","cj"]}
df1= pd.DataFrame(data)

In [ ]:
df1.set_index('c', inplace=True)

In [ ]:
df1

In [ ]:
df1.reset_index(drop=True , inplace= True)

In [ ]:
df1

In [ ]:
df1.reindex([1,2,3,0]) #Conform Series/Dataframe to new index with optional filling logic

In [ ]:
df1

In [ ]:
for i in df1.iterrows(): #rows wise iteration 
    print(i,"____")

In [ ]:
for i in df1.items():
    print(i)

In [ ]:
def func_sum(x):
    return x.sum()

In [ ]:
df1.apply(func_sum , axis =0)

In [ ]:
df1.apply(func_sum , axis = 1)

In [ ]:
df1.applymap(lambda x: x**2)

In [ ]:
data = {"a":[100,200,13,4],
        "b":[5,5,6,7],
        "c":["pw","skills","aj","cj"]}
df2= pd.DataFrame(data)

In [ ]:
df2.sort_values(by='a')

In [ ]:
df

In [ ]:
df.sort_values(by='Fare')

In [ ]:
#pandas lecture 4

In [ ]:
df1 = pd.DataFrame({"description":["Stuck in your job? Learn and grow with our masterclasses led by top industry experts. Dive into tech with seasoned leaders!"]})

In [ ]:
pd.set_option('display.max_colwidth', 1000)

In [ ]:
df1

In [ ]:
#this should display the column and row at max 100 & 100 at a time
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns',100)

In [ ]:
df[:500]

In [ ]:
df1["char_len"]=df1["description"].apply(len)

In [ ]:
df1

In [ ]:
a="I am Ajay"
len(a)

In [22]:
a.split(" ")

NameError: name 'a' is not defined

In [ ]:
len(a.split())

In [ ]:
df1['word_count'] =  df1['description'].apply(lambda x:len(x.split()))

In [ ]:
df1

In [ ]:
data= {'text':['hello data science','I love ML', 'I read ml books']}
a=pd.DataFrame(data)

In [ ]:
a

In [ ]:
a['text_lower'] = a['text'].str.lower()

In [ ]:
a

In [ ]:
a['text_upper'] = a['text'].str.upper()

In [ ]:
a

In [ ]:
a['text'][0].startswith('h')

In [ ]:
df1 = pd.DataFrame({'a':[1,2,4,5,6],
                   'b':[4,5,6,7,8],})

In [ ]:
df1

In [ ]:
df1['mul_a'] = df1['a'] * 5

In [ ]:
df1.a.mean()

In [ ]:
df1.a.median()

In [ ]:
df1.a.mode()

In [ ]:
df1.a.mode()

In [ ]:
df1.a.max()

In [ ]:
df1.a.sum()

In [ ]:
df1.a.std()

In [ ]:
df1.a.var()

In [ ]:
df1.a.describe()

In [ ]:
df2=pd.DataFrame({"a":[1,2,3,4,5,6,7,8,9]})

In [ ]:
df2

In [ ]:
df2.mean()

In [ ]:
df2.rolling(window=1).mean()

In [ ]:
df2.rolling(window=2).mean()

In [ ]:
df3 = df2.rolling(window =3).mean()

In [ ]:
df3.dropna(inplace=True)

In [ ]:
df3.a

In [ ]:
df3['a']

In [ ]:
df3['a_int']=df3['a'].astype(int)

In [ ]:
df3

In [ ]:
df2

In [ ]:
df2.rolling(window=2).sum()

In [ ]:
df2.rolling(window=2).min()

In [ ]:
df2.rolling(window = 2).max()

In [ ]:
df2

In [ ]:
import numpy as np
df2['Group'] = np.random.choice(['A','B'], size= 9)

In [ ]:
df2

In [ ]:
df2['a'].cumsum()

In [ ]:
#data time function vvi

In [ ]:
df=pd.DataFrame({"date": ["22-03-08","2024-03-09","2024-03-10"]})

In [ ]:
df

In [ ]:
df.dtypes #showing data is in  string

In [ ]:
df['updated_date'] = pd.to_datetime(df['date'], format='mixed', dayfirst=True)

In [ ]:


#df['update_date'] = pd.to_datetime(df['date'], errors='coerce')

df['update_date'] = pd.to_datetime(df['date'], format='%d-%m-%Y', errors='coerce')

In [ ]:
df

In [ ]:
df['day']=df['updated_date'].dt.day

In [ ]:
df

In [ ]:
pd.date_range(start='2024-03-10',end ='2025-03-10', freq ='D')  #generate daywise data

In [ ]:
pd.date_range(start='2024-03-10',end='2025-03-10', freq ='h') #hour time generation

In [ ]:
start = pd.Timestamp.now()

In [ ]:
for i in range(1000):
    pass

end = pd.Timestamp.now()
print("time taken", end-start)

In [ ]:
start = pd.Timestamp.now() - pd.DateOffset(weeks=1)
start

In [ ]:
end = pd.Timestamp.now()

In [ ]:
end - start

In [ ]:
from datetime import datetime 
date = '2024-03-24'
date = datetime.strptime(date,"%Y-%m-%d")

In [ ]:
date

In [ ]:
print(date)

In [ ]:
time=pd.Timedelta(days=1, hours = 5, minutes =40)

In [ ]:
time

In [ ]:
dt = pd.to_datetime('2024-03-29')

In [ ]:
dt

In [ ]:
dt+time

In [ ]:
import yfinance as yf

In [ ]:
data =yf.download("PAYTM.NS", start='2023-03-01', end = '2024-03-01')

In [ ]:
data['Close'].resample('M').mean()

In [ ]:
data['Close'].resample('D').mean()

In [ ]:
#ploting function in pandas 
d=pd.Series([1,2,3,4,5,6])

In [ ]:
d.plot()

In [ ]:
data ={"A":[1,2,3],"B":[4,5,6]}

In [ ]:
df=pd.DataFrame(data)

In [ ]:
df.plot()